version: '3'

services:
  web:
    build: ./garden_site
    command:  ./start-django.sh
    container_name: garden-site
    volumes:
      - ./garden_site:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis


  celery_worker:
    build: ./garden_site
    command: ./start-celeryworker.sh
    volumes:
      - ./garden_site:/app
    depends_on:
      - web
      - redis

  celery_beat:
    build: ./garden_site
    command: ./start-celerybeat.sh
    volumes:
      - ./garden_site:/app
    depends_on:
      - web
      - redis



  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
