# Generated by Django 5.0.4 on 2024-05-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathersensor', '0003_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='time',
        ),
    ]
