# Generated by Django 5.0.4 on 2024-05-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathersensor', '0004_remove_weather_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='sunset',
        ),
    ]
