# Generated by Django 5.0.4 on 2024-05-15 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathersensor', '0005_remove_weather_sunrise_remove_weather_sunset'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='sunrise',
            field=models.CharField(default='aaaa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='sunset',
            field=models.CharField(default='bbbbb', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
